version: "3.9"
services:
  mongodb:
    image: mongo:4.4.19
    env_file: .env
    container_name: mymongodb
    environment:
      MONGO_INITDB_DATABASE: mydb
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - ./src/db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro     
    ports:
      - 27017:27017