version: "3.9"
services:
  mymongodb:
    image: mongo:4.4.19
    container_name: "mymongodb"
    restart: always
    environment:
      MONGO_INITDB_ROOT_DATABASE: mydb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./src/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017
    networks:
      - jmeter-app-network
    healthcheck:
      test: [ "CMD", "mongo", "mydb", "--eval", "db.users.find().limit(1)" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 35s
  backend:
    container_name: "backend"
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mymongodb:
        condition: service_healthy
    networks:
      - jmeter-app-network
networks:
  jmeter-app-network: