version: "3.9"
services:
  mymongodb:
    image: mongo:4.4.19
    container_name: "mymongodb"
    environment:
      MONGO_INITDB_ROOT_DATABASE: mydb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ../src/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro     
    ports:
      - 27017:27017
    networks:
      - jmeter-app-network

  backend:
    container_name: "backend"
    build:
      context: .. 
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI:mongodb://admin:admin@mongodb:27017/mydb?authSource=admin
    depends_on:
      - mymongodb
    networks:
      - jmeter-app-network
networks:
    jmeter-app-network:
        driver: bridge