version: "3.9"
services:
  mymongodb:
    image: mongo:4.4.19
    container_name: "mymongodb"
    restart: always
    environment:
      MONGO_INITDB_ROOT_DATABASE: mydb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./src/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017